void __attribute__((noreturn)) __fatal_error(const char *);

void __extendsfdf2() { __fatal_error("not implemented: __extendsfdf2"); }
void __truncdfsf2() { __fatal_error("not implemented: __truncdfsf2"); }
void __eqsf2() { __fatal_error("not implemented: __eqsf2"); }
void __nesf2() { __fatal_error("not implemented: __nesf2"); }
void __ltsf2() { __fatal_error("not implemented: __ltsf2"); }
void __gtsf2() { __fatal_error("not implemented: __gtsf2"); }
void __lesf2() { __fatal_error("not implemented: __lesf2"); }
void __gesf2() { __fatal_error("not implemented: __gesf2"); }
void __eqdf2() { __fatal_error("not implemented: __eqdf2"); }
void __nedf2() { __fatal_error("not implemented: __nedf2"); }
void __ltdf2() { __fatal_error("not implemented: __ltdf2"); }
void __gtdf2() { __fatal_error("not implemented: __gtdf2"); }
void __ledf2() { __fatal_error("not implemented: __ledf2"); }
void __gedf2() { __fatal_error("not implemented: __gedf2"); }
void __divdi3() { __fatal_error("not implemented: __divdi3"); }
void __udivdi3() { __fatal_error("not implemented: __udivdi3"); }
void __moddi3() { __fatal_error("not implemented: __moddi3"); }
void __umoddi3() { __fatal_error("not implemented: __umoddi3"); }
void __addsf3() { __fatal_error("not implemented: __addsf3"); }
void __subsf3() { __fatal_error("not implemented: __subsf3"); }
void __mulsf3() { __fatal_error("not implemented: __mulsf3"); }
void __divsf3() { __fatal_error("not implemented: __divsf3"); }
void __adddf3() { __fatal_error("not implemented: __adddf3"); }
void __subdf3() { __fatal_error("not implemented: __subdf3"); }
void __muldf3() { __fatal_error("not implemented: __muldf3"); }
void __divdf3() { __fatal_error("not implemented: __divdf3"); }
void __fixsfsi() { __fatal_error("not implemented: __fixsfsi"); }
void __fixunssfsi() { __fatal_error("not implemented: __fixunssfsi"); }
void __fixdfsi() { __fatal_error("not implemented: __fixdfsi"); }
void __fixunsdfsi() { __fatal_error("not implemented: __fixunsdfsi"); }
void __fixsfdi() { __fatal_error("not implemented: __fixsfdi"); }
void __fixunssfdi() { __fatal_error("not implemented: __fixunssfdi"); }
void __fixdfdi() { __fatal_error("not implemented: __fixdfdi"); }
void __fixunsdfdi() { __fatal_error("not implemented: __fixunsdfdi"); }
void __floatsisf() { __fatal_error("not implemented: __floatsisf"); }
void __floatunsisf() { __fatal_error("not implemented: __floatunsisf"); }
void __floatdisf() { __fatal_error("not implemented: __floatdisf"); }
void __floatundisf() { __fatal_error("not implemented: __floatundisf"); }
void __floatsidf() { __fatal_error("not implemented: __floatsidf"); }
void __floatunsidf() { __fatal_error("not implemented: __floatunsidf"); }
void __floatdidf() { __fatal_error("not implemented: __floatdidf"); }
void __floatundidf() { __fatal_error("not implemented: __floatundidf"); }
void _exit() { __fatal_error("not implemented: _exit"); }
void _sbrk() { __fatal_error("not implemented: _sbrk"); }
void _kill() { __fatal_error("not implemented: _kill"); }
void _getpid() { __fatal_error("not implemented: _getpid"); }
void _close() { __fatal_error("not implemented: _close"); }
void _lseek() { __fatal_error("not implemented: _lseek"); }
void _read() { __fatal_error("not implemented: _read"); }
void _times() { __fatal_error("not implemented: _times"); }
void __trunctfdf2() { __fatal_error("not implemented: __trunctfdf2"); }
void _write() { __fatal_error("not implemented: _write"); }
int _fstat() { return -1; }
void _isatty() { __fatal_error("not implemented: _isatty"); }
